// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0--rc3
// source: proto/loggerbin.proto

package loggerbin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoggerbinServiceClient is the client API for LoggerbinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoggerbinServiceClient interface {
	AddLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error)
}

type loggerbinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggerbinServiceClient(cc grpc.ClientConnInterface) LoggerbinServiceClient {
	return &loggerbinServiceClient{cc}
}

func (c *loggerbinServiceClient) AddLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/loggerbin.LoggerbinService/AddLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerbinServiceServer is the server API for LoggerbinService service.
// All implementations must embed UnimplementedLoggerbinServiceServer
// for forward compatibility
type LoggerbinServiceServer interface {
	AddLog(context.Context, *LogRequest) (*Empty, error)
	mustEmbedUnimplementedLoggerbinServiceServer()
}

// UnimplementedLoggerbinServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoggerbinServiceServer struct {
}

func (UnimplementedLoggerbinServiceServer) AddLog(context.Context, *LogRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLog not implemented")
}
func (UnimplementedLoggerbinServiceServer) mustEmbedUnimplementedLoggerbinServiceServer() {}

// UnsafeLoggerbinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggerbinServiceServer will
// result in compilation errors.
type UnsafeLoggerbinServiceServer interface {
	mustEmbedUnimplementedLoggerbinServiceServer()
}

func RegisterLoggerbinServiceServer(s grpc.ServiceRegistrar, srv LoggerbinServiceServer) {
	s.RegisterService(&LoggerbinService_ServiceDesc, srv)
}

func _LoggerbinService_AddLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerbinServiceServer).AddLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/loggerbin.LoggerbinService/AddLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerbinServiceServer).AddLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoggerbinService_ServiceDesc is the grpc.ServiceDesc for LoggerbinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoggerbinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loggerbin.LoggerbinService",
	HandlerType: (*LoggerbinServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLog",
			Handler:    _LoggerbinService_AddLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/loggerbin.proto",
}
